web:
    image: hitalos/laravel:latest
    ports:
        - 8088:80
    volumes:
        - ./:/var/www
    links:
        - db
    container_name: web
    
    environment:
        DB_HOST: db
        DB_DATABASE: dbname
        DB_USERNAME: username
        DB_PASSWORD: p455w0rd
        DB_CONNECTION: mysql
db:
    image: mysql
    ports:
        - 8081:3306
    container_name: db
    environment:
        # with mysql
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dbname
        MYSQL_USER: username
        MYSQL_PASSWORD: p455w0rd
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        
